import Provider from '@components/Provider'
import '../Styles/globals.css'
import Nav from '../components/Nav'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Provider>
        <main className=' w-full flex flex-col items-center'>
        <Nav></Nav>
        {children}
        </main>
        </Provider>
      </body>
    </html>
  )
}
